export const SYMPTOMS = [
  { id: 'holes_on_head', label: 'Holes On Head' },
  { id: 'pitting_on_head', label: 'Pitting On Head' },
  { id: 'white_feces', label: 'White Feces' },
  { id: 'loss_of_appetite', label: 'Loss Of Appetite' },
  { id: 'lethargy', label: 'Lethargy' },
  { id: 'dark_coloration', label: 'Dark Coloration' },
  { id: 'body_turning_black', label: 'Body Turning Black' },
  { id: 'clamped_fins', label: 'Clamped Fins' },
  { id: 'hiding_behavior', label: 'Hiding Behavior' },
  { id: 'damaged_fins', label: 'Damaged Fins' },
  { id: 'frayed_fins', label: 'Frayed Fins' },
  { id: 'white_edges_on_fins', label: 'White Edges On Fins' },
  { id: 'red_inflamed_fins', label: 'Red Inflamed Fins' },
  { id: 'fin_discoloration', label: 'Fin Discoloration' },
  { id: 'normal_swimming', label: 'Normal Swimming' },
  { id: 'clear_body', label: 'Clear Body' },
  { id: 'good_appetite', label: 'Good Appetite' },
  { id: 'active_behavior', label: 'Active Behavior' },
  { id: 'normal_fins', label: 'Normal Fins' },
];
